apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-notifier
  namespace: dev
  labels:
    type: main
    app: deployment-notifier
spec:
  selector:
    matchLabels:
      type: main
      app: deployment-notifier
  replicas: 1
  template:
    metadata:
      labels:
        type: main
        app: deployment-notifier
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: deployment-notifier
          image: pdvoinos/deployment-slack-notifier:0.6
          imagePullPolicy: Always
          env:           
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: deploy-notify
                  key: slack-token
            - name: SLACK_CHANNEL
              value: "#dev-deploys"
            - name: SLACK_ICON
              value: ":kubernetes:"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: deploy-notify
                  key: github-token
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 60
            failureThreshold: 1
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 200Mi
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 200Mi
