apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceaccount-read-pods
rules:
  - apiGroups: ["*"] # "extensions"
    resources: ["deployments", "deployments/scale", "pods", replicasets]
    verbs: ["get", "list"]
  - apiGroups: [ "*" ]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: serviceaccount-read-pods-rb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev
roleRef:
  kind: ClusterRole
  name: serviceaccount-read-pods
  apiGroup: ""